language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag reverseproxy hauhuong/reverseproxy
  - docker tag udagram-api-user hauhuong/udagram-api-user
  - docker tag udagram-api-feed hauhuong/udagram-api-feed
  - docker tag udagram-frontend hauhuong/udagram-frontend


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hauhuong/reverseproxy
  - docker push hauhuong/udagram-api-user
  - docker push hauhuong/udagram-api-feed
  - docker push hauhuong/udagram-frontend