version: "3"
services:
  hauhuong_reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  hauhuong_backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  hauhuong_backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  hauhuong_frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local